name: Swift

on:
  push:
    branches: [ ios_develop ]
  pull_request:
    branches: [ ios_release ]
  
jobs: 
      build:
        runs-on: [macos-latest] 
        env: 
          XC_VERSION: ${{ '12.1.0' }}
          XC_PROJECT: ${{ 'IssueTracker.xcworkspace' }}
          XC_SCHEME: ${{ 'IssueTrackerTest' }} 
        steps: 
        - name: Select latest Xcode 
          run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app" 
        - name: Install Dependencies
          run: |
            cd iOS/IssueTracker
            pod install --repo-update
          shell: bash
        - name: CocoaPods Action
          uses: ty0x2333/cocoapods-action@0.2.0
          with:
            additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'          
          
       
